name = "inpi-proxy-nft"
main = "src/index.ts"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]

[vars]
UPSTREAM_RPC = "https://api.mainnet-beta.solana.com"
ALLOWED_ORIGINS = "https://mint.inpinity.online,https://inpinity.online"
REMOTE_CLAIMS_URL = ""
[[kv_namespaces]]
binding = "CLAIMS"
id = "139ec0627b02429db4507c14b5a3a1fd"

# NUR wenn du die Route wirklich neu setzen willst:
# (Vorher im Dashboard sicherstellen, dass sie frei ist)
routes = [
  { pattern = "inpinity.online/mint/*", zone_name = "inpinity.online" }
]