name = "inpi-proxy-nft"               # <- benutze den aktiven Worker-Namen
main = "src/index.ts"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]

# ==== Umgebungsvariablen ====
[vars]
UPSTREAM_RPC = "https://api.mainnet-beta.solana.com"
BACKUP_RPC   = "https://solana.publicnode.com"

ALLOWED_ORIGINS = "https://inpinity.online,https://mint.inpinity.online,https://inpinity-mint.pages.dev"
ALLOWED_HEADERS = "content-type,solana-client,accept,accept-language"

REMOTE_CLAIMS_URL = ""
CREATOR_PUBKEY = "GEFoNLncuhh4nH99GKvVEUxe59SGe74dbLG7UUtfHrCp"
MAX_INDEX = "9999"

# ==== KV Bindings ====
[[kv_namespaces]]
binding = "CLAIMS"
id = "139ec0627b02429db4507c14b5a3a1fd"
# NEU: MINTS-Registry
[[kv_namespaces]]
binding = "MINTS"
id = "<139ec0627b02429db4507c14b5a3a1fd>"

[[kv_namespaces]]
binding = "VENDOR"
# erst in CF-Dashboard anlegen, ID hier eintragen:
id = "<a6bf0aa165cf4be7b2a6621004175315>"

# ==== Route ====
routes = [
  { pattern = "api.inpinity.online/*", zone_name = "inpinity.online" }
]